using System.Runtime.CompilerServices;
using System.Text;

namespace LingFanEngine.SDK.Cryptography;

/// <summary>
/// 生成 GeneratedKeys.cs 源代码文件
/// <para>密钥分片写入多个 static readonly byte[] 数组，防完整提取</para>
/// <para>[AggressiveInlining] 在 AOT 编译时内联，密钥字节折叠为机器码常量</para>
/// </summary>
public static class KeyInjector
{
    /// <summary>
    /// 生成 GeneratedKeys.cs 源代码
    /// </summary>
    /// <param name="namespaceName">用户项目命名空间（如 MyGame.Security）</param>
    /// <param name="key">32 字节 AES-256 密钥</param>
    /// <param name="shardCount">分片数（默认 4）</param>
    public static string GenerateKeyFile(string namespaceName, byte[] key, int shardCount = 4)
    {
        var shards = KeyManager.ShardKey(key, shardCount);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>由 LingFanEngine.SDK 生成——请勿手动修改</auto-generated>");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 加密密钥（分片存储，AOT 编译时内联为机器码常量）");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class GeneratedKeys");
        sb.AppendLine("{");

        for (var i = 0; i < shards.Length; i++)
        {
            sb.AppendLine($"    private static readonly byte[] _s{i + 1} = {{ {FormatBytes(shards[i])} }};");
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 获取组合后的完整密钥");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    internal static byte[] GetKey()");
        sb.AppendLine("    {");
        sb.AppendLine("        var key = new byte[32];");

        var shardSize = 32 / shardCount;
        for (var i = 0; i < shards.Length; i++)
        {
            sb.AppendLine($"        _s{i + 1}.CopyTo(key, {i * shardSize});");
        }

        sb.AppendLine("        return key;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>格式化 byte[] 为 C# 数组初始化语法</summary>
    private static string FormatBytes(byte[] bytes)
    {
        var parts = new string[bytes.Length];
        for (var i = 0; i < bytes.Length; i++)
        {
            parts[i] = $"0x{bytes[i]:X2}";
        }
        return string.Join(", ", parts);
    }
}
