using System.Runtime.CompilerServices;
using System.Text;
using LingFanEngine.Abstractions.Interfaces.Core;

namespace LingFanEngine.SDK.Cryptography;

/// <summary>
/// 生成 GeneratedKeys.cs 源代码文件
/// <para>密钥分片写入多个 static readonly byte[] 数组（IL 元数据分散防批量提取），
/// 类型静态构造时合为一个 _combined 数组，GetKey() 返回 ReadOnlySpan&lt;byte&gt; 零分配。</para>
/// <para>同时生成 GeneratedKeyProvider 实现 IEncryptionKeyProvider 接口，供 DI 注册。</para>
/// <para>[AggressiveInlining] 在 AOT 编译时内联，密钥字节折叠为机器码常量。</para>
/// </summary>
public static class KeyInjector
{
    /// <summary>
    /// 生成 GeneratedKeys.cs 源代码（含 GeneratedKeys + GeneratedKeyProvider）
    /// </summary>
    /// <param name="namespaceName">用户项目命名空间（如 MyGame.Security）</param>
    /// <param name="key">32 字节 AES-256 密钥</param>
    /// <param name="shardCount">分片数（默认 4，1 = 不分片）</param>
    public static string GenerateKeyFile(string namespaceName, byte[] key, int shardCount = 4)
    {
        var shards = KeyManager.ShardKey(key, shardCount);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>由 LingFanEngine.SDK 生成——请勿手动修改</auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using LingFanEngine.Abstractions.Interfaces.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 加密密钥（分片存储，AOT 编译时内联为机器码常量）");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class GeneratedKeys");
        sb.AppendLine("{");

        if (shards.Length == 1)
        {
            // 不分片——单数组直接输出
            sb.AppendLine($"    private static readonly byte[] _combined =");
            sb.AppendLine($"        {{ {FormatBytesMultiline(shards[0], 8)} }};");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>获取完整密钥（零分配 ReadOnlySpan）</summary>");
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    internal static ReadOnlySpan<byte> GetKey() => _combined.AsSpan();");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>获取完整密钥（byte[] 重载，供 IEncryptionKeyProvider 使用。返回内部数组引用——调用者不得修改）</summary>");
            sb.AppendLine("    internal static byte[] GetKeyArray() => _combined;");
        }
        else
        {
            // 分片——多个小数组，静态构造时合并
            for (var i = 0; i < shards.Length; i++)
            {
                sb.AppendLine($"    private static readonly byte[] _s{i + 1} =");
                sb.AppendLine($"        {{ {FormatBytesMultiline(shards[i], 8)} }};");
            }

            sb.AppendLine();
            sb.AppendLine("    /// <summary>组合后的完整密钥（静态构造时一次性合并）</summary>");
            sb.AppendLine("    private static readonly byte[] _combined = CombineShards();");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>获取完整密钥（零分配 ReadOnlySpan）</summary>");
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    internal static ReadOnlySpan<byte> GetKey() => _combined.AsSpan();");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>获取完整密钥（byte[] 重载，供 IEncryptionKeyProvider 使用。返回内部数组引用——调用者不得修改）</summary>");
            sb.AppendLine("    internal static byte[] GetKeyArray() => _combined;");
            sb.AppendLine();

            // 生成 CombineShards 方法
            sb.AppendLine("    private static byte[] CombineShards()");
            sb.AppendLine("    {");
            sb.AppendLine("        var key = new byte[32];");
            var offset = 0;
            for (var i = 0; i < shards.Length; i++)
            {
                sb.AppendLine($"        _s{i + 1}.CopyTo(key, {offset});");
                offset += shards[i].Length;
            }
            sb.AppendLine("        return key;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // 生成 IEncryptionKeyProvider 实现——DI 注册用
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 加密密钥提供者——将 GeneratedKeys 接入引擎 DI。");
        sb.AppendLine("/// 在 ServiceExtensions 中注册：services.AddSingleton&lt;IEncryptionKeyProvider, GeneratedKeyProvider&gt;();");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal sealed class GeneratedKeyProvider : IEncryptionKeyProvider");
        sb.AppendLine("{");
        sb.AppendLine("    public byte[]? GetKey() => GeneratedKeys.GetKeyArray();");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>格式化 byte[] 为 C# 数组初始化语法（多行，每行 maxPerLine 字节）</summary>
    private static string FormatBytesMultiline(byte[] bytes, int maxPerLine)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < bytes.Length; i++)
        {
            if (i > 0)
                sb.Append(", ");
            if (i > 0 && i % maxPerLine == 0)
                sb.AppendLine().Append("          ");

            sb.Append($"0x{bytes[i]:X2}");
        }
        return sb.ToString();
    }
}
