// <auto-generated>由 LingFanEngine.SDK 生成——请勿手动修改</auto-generated>
#nullable enable
using System.Runtime.CompilerServices;
using LingFanEngine.Abstractions.Interfaces.Core;

namespace LingFanEngine.Entry.Security;

/// <summary>
/// 加密密钥（分片存储，AOT 编译时内联为机器码常量）
/// </summary>
internal static class GeneratedKeys
{
    private static readonly byte[] _s1 =
        { 0x00, 0x12, 0xFC, 0xE8, 0xA1, 0xE5, 0x3D, 0x0F };
    private static readonly byte[] _s2 =
        { 0x38, 0x5D, 0x00, 0xD7, 0xF6, 0x69, 0xDC, 0x04 };
    private static readonly byte[] _s3 =
        { 0xFA, 0xA0, 0x44, 0xE4, 0xFC, 0xC1, 0x76, 0xBB };
    private static readonly byte[] _s4 =
        { 0x5A, 0x6B, 0x8A, 0x85, 0xE7, 0xD8, 0x63, 0x24 };

    /// <summary>组合后的完整密钥（静态构造时一次性合并）</summary>
    private static readonly byte[] _combined = CombineShards();

    /// <summary>获取完整密钥（零分配 ReadOnlySpan）</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static ReadOnlySpan<byte> GetKey() => _combined.AsSpan();

    /// <summary>获取完整密钥（byte[] 重载，供 IEncryptionKeyProvider 使用。返回内部数组引用——调用者不得修改）</summary>
    internal static byte[] GetKeyArray() => _combined;

    private static byte[] CombineShards()
    {
        var key = new byte[32];
        _s1.CopyTo(key, 0);
        _s2.CopyTo(key, 8);
        _s3.CopyTo(key, 16);
        _s4.CopyTo(key, 24);
        return key;
    }
}

/// <summary>
/// 加密密钥提供者——将 GeneratedKeys 接入引擎 DI。
/// 在 ServiceExtensions 中注册：services.AddSingleton&lt;IEncryptionKeyProvider, GeneratedKeyProvider&gt;();
/// </summary>
internal sealed class GeneratedKeyProvider : IEncryptionKeyProvider
{
    public byte[]? GetKey() => GeneratedKeys.GetKeyArray();
}
