// <auto-generated>由 LingFanEngine.SDK 生成——请勿手动修改</auto-generated>
// 开发期占位文件——构建加密时由 KeyInjector 替换为真实密钥
#nullable enable
using LingFanEngine.Abstractions.Interfaces.Core;

namespace _LingFanEngineTemplateTitle_.Security;

/// <summary>
/// 加密密钥（开发期占位——返回 null 表示无加密）
/// </summary>
internal static class GeneratedKeys
{
    /// <summary>获取完整密钥（零分配 ReadOnlySpan）</summary>
    internal static ReadOnlySpan<byte> GetKey() => default;

    /// <summary>获取完整密钥（byte[] 重载，供 IEncryptionKeyProvider 使用）</summary>
    internal static byte[]? GetKeyArray() => null;
}

/// <summary>
/// 加密密钥提供者——将 GeneratedKeys 接入引擎 DI。
/// 在 ServiceExtensions 中注册：services.AddSingleton&lt;IEncryptionKeyProvider, GeneratedKeyProvider&gt;();
/// </summary>
internal sealed class GeneratedKeyProvider : IEncryptionKeyProvider
{
    public byte[]? GetKey() => GeneratedKeys.GetKeyArray();
}
